#Use an official Maven image to build the spring boot app
FROM maven : 

# Use official lightweight OpenJDK image
FROM openjdk:21-jdk


# Set working directory in the container
WORKDIR /app


# Optionally copy credential.properties if you want to use it inside container
COPY credential.properties /app/credential.properties

# Copy your Spring Boot jar file to the container
COPY target/Skill_Swap_Backend-0.0.1-SNAPSHOT.jar app.jar

# Set the working directlory
WORKDIR /app

#Copy the build JAR file from the build stage
COPY --from=build /app/target/Skill_Swap_Backend-0.0.1-SNAPSHOT.jar

# Expose port 8080
EXPOSE 8080

# Run the app
ENTRYPOINT ["java", "-jar", "/app/Skill_Swap_Backend-0.0.1-SNAPSHOT.jar"]
